<?php require_once '../../config/database.php'; if(!isAdmin()) redirect('/ecommerce/modulos/auth/login.php');
$db=getDB();$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){$did=intval($_POST['id']);$e=$_POST['estado'];$db->query("UPDATE pedidos SET estado='$e' WHERE id=$did");auditar($_SESSION['user_id'],'cambiar_estado','pedidos',"#$did→$e");$msg="Pedido #$did actualizado.";}
$ps=$db->query("SELECT p.*,u.nombre,u.apellido,u.email FROM pedidos p JOIN usuarios u ON p.usuario_id=u.id ORDER BY p.created_at DESC");
?><!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Pedidos</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"><style>.s{background:#1a1a2e;min-height:100vh;color:white;position:fixed;width:220px}.s a{color:rgba(255,255,255,.7);padding:10px 15px;display:block;text-decoration:none}.s a:hover,.s a.ac{background:rgba(255,255,255,.1);color:white}.m{margin-left:220px;padding:20px}</style></head><body>
<div class="s p-3"><h5 class="text-white mb-3">Admin</h5><a href="dashboard.php">📊 Dashboard</a><a href="productos.php">📦 Productos</a><a href="pedidos.php" class="ac">🧾 Pedidos</a><a href="inventario.php">📋 Inventario</a><a href="/ecommerce/">← Sitio</a></div>
<div class="m"><h2>Pedidos</h2><?php if($msg):?><div class="alert alert-success"><?=$msg?></div><?php endif;?>
<table class="table table-sm"><thead><tr><th>#</th><th>Cliente</th><th>Total</th><th>Estado</th><th>Fecha</th><th></th></tr></thead><tbody>
<?php while($p=$ps->fetch_assoc()):?><tr><td>#<?=$p['id']?></td><td><?=htmlspecialchars($p['nombre'].' '.$p['apellido'])?></td><td>$<?=number_format($p['total'],0)?></td><td><form method="post" class="d-flex gap-1"><input type="hidden" name="id" value="<?=$p['id']?>"><select name="estado" class="form-select form-select-sm" onchange="this.form.submit()"><?php foreach(['pendiente','pagado','enviado','entregado','cancelado'] as $s):?><option value="<?=$s?>" <?=$p['estado']==$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></form></td><td><?=date('d/m/Y',strtotime($p['created_at']))?></td><td><a href="#" class="btn btn-sm btn-outline-secondary">Ver</a></td></tr><?php endwhile;?></tbody></table></div></body></html>
