CREATE DATABASE IF NOT EXISTS ecommerce_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ecommerce_db;

CREATE TABLE usuarios (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL, apellido VARCHAR(100) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, rol ENUM('cliente','admin') DEFAULT 'cliente', activo TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE categorias (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) UNIQUE NOT NULL, icono VARCHAR(50) DEFAULT 'bi-tag', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE productos (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(255) NOT NULL, descripcion TEXT, precio DECIMAL(10,2) NOT NULL, stock INT DEFAULT 0, categoria_id INT, imagen VARCHAR(255) DEFAULT 'assets/img/default.png', destacado TINYINT(1) DEFAULT 0, activo TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE pedidos (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, total DECIMAL(10,2) NOT NULL, estado ENUM('pendiente','pagado','enviado','entregado','cancelado') DEFAULT 'pendiente', direccion_envio TEXT, notas TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (usuario_id) REFERENCES usuarios(id)) ENGINE=InnoDB;
CREATE TABLE detalle_pedido (id INT AUTO_INCREMENT PRIMARY KEY, pedido_id INT NOT NULL, producto_id INT NOT NULL, cantidad INT DEFAULT 1, precio_unitario DECIMAL(10,2) NOT NULL, FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE, FOREIGN KEY (producto_id) REFERENCES productos(id)) ENGINE=InnoDB;
CREATE TABLE movimientos_inventario (id INT AUTO_INCREMENT PRIMARY KEY, producto_id INT NOT NULL, tipo ENUM('entrada','salida') NOT NULL, cantidad INT NOT NULL, motivo VARCHAR(200), pedido_id INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (producto_id) REFERENCES productos(id), FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE auditoria (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT, accion VARCHAR(200) NOT NULL, tabla_afectada VARCHAR(100), descripcion TEXT, ip VARCHAR(45), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL) ENGINE=InnoDB;
INSERT INTO categorias (nombre, icono) VALUES ('Electrónica','bi-laptop'),('Ropa','bi-handbag'),('Hogar','bi-house'),('Deportes','bi-bicycle'),('Libros','bi-book'),('Alimentos','bi-basket'),('Juguetes','bi-controller'),('Salud','bi-heart-pulse'),('Automotriz','bi-car-front'),('Oficina','bi-briefcase');
INSERT INTO usuarios (nombre, apellido, email, password_hash, rol) VALUES ('Admin','Sistema','admin@ecommerce.cl','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi','admin');
